ucfopen/canvasapi

- canvasapi/course.py
- canvasapi/external_feed.py
- canvasapi/group.py
- tests/fixtures/course.json
- tests/fixtures/group.json
- tests/test_course.py
- tests/test_external_feed.py
- tests/test_group.py
Completes issue #18 
Added:
- List external feeds
- Create an external feed
- Delete an external feed
> added support for external feeds

- DEPLOY.md
- README.md
Moved documentation to Read the Docs. (http://canvasapi.readthedocs.io/) Updated links as necessary. Added explicit Documentation section to the wiki with a link to RTD.
Resolves #44
> Move Documentation to Read the Docs

- canvasapi/canvas.py
- tests/fixtures/account.json
- tests/fixtures/course.json
- tests/fixtures/group.json
- tests/fixtures/section.json
- tests/test_canvas.py
Added optional `use_sis_id` argument to methods for getting an account, course, group and section. Allows use of SIS IDs in appropriate id variables.
Resolves #50
> Expand SIS ID Support

- .travis.yml
- setup.cfg
`flake8` is a wrapper around `pyflakes`, `pycodestyle`, and `mccabe`, and also can be further extended using third-party plugins.  The Travis-CI tests were already running `pyflakes` and `pycodestyle`.  We may as well unify both of those under the `flake8` umbrella so that we have a single place to manage configuration, unified output of any complaints, etc.
Note: if the `canvasapi` developers want to support `flake8` but prefer to retain the option of running `pycodestyle` directly as well, then my changes to `setup.cfg` should be changed slightly. Instead of renaming the `[pycodestyle]` section to `[flake8]`, there should instead be two sections, one named `[pycodestyle]` and one named `[flake8]`, both with the same `max-line-length = 99` content. I am happy to revise this pull request …
> Use flake8 instead of pyflakes and pycodestyle

- .gitignore
Per closed pull request #67, the maintainers’ consensus is that such configuration files should be excluded from source control.
> Ignore Eclipse and PyDev project metadata

- CONTRIBUTING.md
`git branch` does not take a `-b` flag.  To create a new branch and check it out, one should use `git checkout -b`, not `git branch -b`.
> Correct the git command used to create and check out a new branch

- canvasapi/page.py
Fixed an error where editing a page would try to access a non-existent ID instead of the course ID 
Resolves #72
> Page Edit Fail

- canvasapi/course.py
- canvasapi/section.py
- tests/test_course.py
- tests/test_section.py
Added warning for using `grouped` param in submissions. Delete `grouped` param if used rather than overriding to `False` (which doesn't work due to Canvas' terrible boolean handling)
Resolves #61
> Grouped Submission Response

- .gitignore
- canvasapi/course.py
- canvasapi/requester.py
- canvasapi/section.py
- canvasapi/submission.py
- tests/fixtures/submission.json
- tests/test_course.py
- tests/test_group.py
- tests/test_submission.py
- tests/test_uploader.py
- tests/test_user.py
- tests/util.py
Adds coverage for the [Submission Comments Upload a File](https://canvas.instructure.com/doc/api/submission_comments.html#method.submission_comments_api.create_file) endpoint.
Also moves file cleanup in tests to its own function in utils.
Resolves #79
> Submission Comment File Upload

- canvasapi/course.py
- canvasapi/group.py
- canvasapi/util.py
- tests/test_util.py
Following the fix of issue #55 by pull request #63, canvasapi parameter handling treated any `list` or `tuple` as a sequence of multiple values.  When a caller provide multiple values in this way, they are be turned into repeated `param[]=...` parameters in an eventual Canvas API call.
The current pull request generalizes that support to *any* iterable collection of values, not just list and tuple.  One can now pass multiple values using `list` or `tuple` as before, but also `set`, generators, iterable objects returned by `zip` and `ichain`, etc. Strings and byte sequences are special cases.  Although these are iterable, each is treated a single value rather than as a sequence of isolated characters or bytes.
If accepted, this pull request will resolve issue #94.
> Issue #94: Generalize repeated "param[]=..." support to all iterables

- canvasapi/canvas.py
- tests/fixtures/user.json
- tests/test_canvas.py
Fixes an issue where `Canvas.get_user()` stopped accepting `'self'` as a valid value for the `user` param.
Resolves #109
> Issue #109 get user self

- canvasapi/canvas.py
- tests/fixtures/conversation.json
- tests/test_canvas.py
Fixes an issue where the `create_conversation` method wouldn't actually create the conversation until the results were iterated over.
Instead of returning a PaginatedList (which is unnecessary), am just returning a `list` of `Conversation` objects directly.
Resolves #102
> Create Conversation Fix

- canvasapi/util.py
- tests/test_util.py
Fixed an issue where a list as a value of a dictionary passed to `combine_kwargs` would incorrectly put empty brackets before the key.
Specifically, 
```python
method(dict_list={
'key': ['item1', 'item2']
})
```
**Incorrectly** returned
```
dict_list[][key]=item1
dict_list[][key]=item2
```
But now **correctly** returns
```
dict_list[key][]=item1
dict_list[key][]=item2
```
> Combine Kwargs Fix

- canvasapi/requester.py
- tests/test_requester.py
Resolves #150 and by extension #64.
> #150 Lowercase boolean values

- canvasapi/course.py
- canvasapi/group.py
- canvasapi/tab.py
- docs/class-reference.rst
- docs/enrollment-ref.rst
- docs/tab-ref.rst
- tests/test_course.py
- tests/test_tab.py
Per #168, deprecate `Course.update_tab` and move method to `Tab.update()`. Added docs.
> Issue #168 Update Tab

- AUTHORS.md
- CHANGELOG.md
- canvasapi/quiz.py
- docs/quiz-ref.rst
- tests/fixtures/quiz.json
- tests/test_quiz.py
Hi, I've added [`get all quiz submissions`][1] endpoint, and updated tests.
[1]: https://canvas.instructure.com/doc/api/quiz_submissions.html#method.quizzes/quiz_submissions_api.index
> Add `get all quiz submissions` endpoint

- CHANGELOG.md
- canvasapi/course.py
- canvasapi/section.py
- canvasapi/submission.py
- canvasapi/util.py
- tests/fixtures/course.json
- tests/fixtures/section.json
- tests/test_course.py
- tests/test_section.py
- tests/test_submission.py
- tests/test_util.py
* Create a new `GroupedSubmission` class that wraps around multiple `Submission` objects.
* Change how `course.get_multiple_submissions` reacts when the `grouped` parameter is passed: Returns a `PaginatedList` of `GroupedSubmission` objects instead of throwing a warning and deleting the `grouped` parameter.
* Formatting tweaks
Fixes #77.
> Grouped Submissions

- AUTHORS.md
- CHANGELOG.md
- canvasapi/canvas.py
- canvasapi/course.py
- canvasapi/section.py
- tests/test_course.py
- tests/test_group.py
- tests/test_outcome.py
- tests/test_page.py
- tests/test_section.py
- tests/test_submission.py
- tests/test_user.py
* Remove overzealous global enabling of `DeprecationWarning`
* Turns on `DeprecationWarning` for tests (Python 2.7 doesn't enable automatically)
Fixes #284.
> Remove DeprecationWarning

- dev_requirements.txt
* Remove svn install of `docutils` in favor of the (finally) updated version on PyPI.
> Upgrade docutils

- CHANGELOG.md
- canvasapi/canvas.py
- canvasapi/util.py
- tests/test_canvas.py
- tests/test_util.py
This PR fixes a bug introduced in [!281](https://github.com/ucfopen/canvasapi/pull/281/), where accidental trailing spaces would trigger a ValueError in `util.clean_headers()`.
* Add a sanitization step in `Canvas.__init__()` to strip leading and trailing spaces from API keys.
* Update `util.clean_headers()` to remove the offending call to `split()`, returning the last four digits of the `Authorization` header regardless of its contents.
Fixes #301.
> #301 Spaces in API_KEY throw ValueError

- canvasapi/paginated_list.py
- tests/test_paginated_list.py
* Fix https://github.com/ucfopen/canvasapi/issues/305 by throwingIndexError whenever a negative index is requested.
* As a bonus, do the same when a slice is requested rather than when it's used.
Fixes #305.
> Never allow negative indexing of the PaginatedList

- .github/CONTRIBUTING.md
In CONTRIBUTING.md, `Running tests / coverage reports` does not link correctly to its content.
> CONTRIBUTING.md does not link correctly

- canvasapi/canvas.py
- canvasapi/course.py
In general, calls on Canvas to URLs that return users accept additional optional arguments such as include. This PR adds additional keyword arguments for those calls.
> Add additional keyword arguments for get_user call

- canvasapi/submission.py
- tests/test_submission.py
* Fixes an issue where `submissions` weren't in `attributes` of GroupedSubmission.
Fixes #303.
> GroupedSubmission submissions key:value deleted

- canvasapi/quiz.py
Hi! It seems like creating a report on a quiz currently does not work. The Canvas api [expects](https://github.com/instructure/canvas-lms/blob/master/app/controllers/quizzes/quiz_reports_controller.rb#L159) the report type to be passed as `quiz_report[report_type]`, but canvasapi passes it as `report_type`. This causes an error like:
```
~/code/canvasapi/canvasapi/requester.py in request(self, method, endpoint, headers, use_auth, _url, _kwargs, **kwargs)
220         # Raise for status codes
221         if response.status_code == 400:
--> 222             raise BadRequest(response.text)
223         elif response.status_code == 401:
224             if "WWW-Authenticate" in response.headers:
BadRequest: {"status":"bad_request","message":"invalid quiz report type","error_report_id":53209570} …
```
> Pass report_type param correctly in create_report

- tests/test_course.py
- tests/test_group.py
- tests/test_user.py
Fixing all instances of var `l` (which flake8 hates) to `lic` in 3 tests.
Resolves #373
> changing all instances of l to lic in relevant tests to appease flake8

- canvasapi/course.py
- tests/fixtures/course.json
- tests/test_course.py
This provides coverage for the courses/:course_id/folders/by_path/*full_path endpoint along with a basic unit test.
Fixes #375
> adding coverage for resolve_path

- canvasapi/canvas.py
- tests/settings.py
- tests/test_canvas.py
* Strip base URLs in addition to access tokens while initializing a Canvas client
Fixes #370 .
> #370 Strip trailing and leading spaces from base URLs

- AUTHORS.md
- CHANGELOG.md
- canvasapi/quiz.py
- tests/fixtures/quiz.json
- tests/fixtures/quiz_group.json
- tests/test_quiz.py
- tests/test_quiz_group.py
Previously, Quiz.get_quiz_group set the course ID of the quiz group to be the ID of the quiz. This caused errors when using the constructed QuizGroup to make requests as the course ID was incorrect causing the URL to be incorrect. This change fixes that issue by setting the course ID of the quiz group to be the course ID of the course the quiz is contained in.
> Fix Quiz Group Course ID

- CHANGELOG.md
- canvasapi/course.py
- tests/test_course.py
* Remove positional arguments from `Course.create_external_tool` to allow `client_id` to be passed for LTI 1.3 support.
Fixes #402.
> Issue #402 Create External Tool - Client ID

- canvasapi/canvas.py
- tests/test_canvas.py
`canvas.get_todo_items` returns a `PaginatedList` of `Todo` items.
Fixes #444
> Fixes #444

- canvasapi/assignment.py
Resolves two minor typos in `assignment.py` that result in invalid syntax.
Discovered when running doctests over the codebase for an unrelated branch.
> Fix typos in assignment.py

- CHANGELOG.md
- canvasapi/exceptions.py
- canvasapi/requester.py
- docs/exceptions.rst
- tests/fixtures/requests.json
- tests/test_requester.py
* Add a new exception `RateLimitExceeded` to handle 403 responses with content `403 Forbidden (Rate Limit Exceeded)`
Fixes #466
> Issue #466 Add RateLimitExceeded Exception

- CHANGELOG.md
- canvasapi/canvas.py
- tests/test_canvas.py
- tests/test_poll.py
* Fix incorrect param in Canvas.create_poll (`poll` -> `polls`)
* Relocate `create_poll` tests to `test_canvas.py`
Fixes #470.
> Fix Create Poll Parameter

- CHANGELOG.md
- canvasapi/course.py
- canvasapi/rubric.py
- tests/fixtures/rubric.json
- tests/test_course.py
- tests/test_rubric.py
Addresses Issue #480 by adding a delete function to the Rubric class in rubric.py that calls the Rubric DELETE endpoint in the Canvas LMS REST API.
Sorry for the multiple pull requests - for some reason we failed a run on Github the first time.
> Issue/480 Add Support for Delete Rubric

- CHANGELOG.md
- canvasapi/content_migration.py
- docs/content-migration-ref.rst
- tests/fixtures/content_migration.json
- tests/test_content_migration.py
* Add get_selective_data() to canvasapi.content_migration.ContentMIgration to return nodes available for selection when a migration is created with selective_import=true
Fixes #502
> Issue #502: Add endpoint to get selective_data for a content migration

- .github/workflows/run-tests.yml
- CHANGELOG.md
- dev_requirements.txt
- setup.py
- tests_requirements.txt
- Remove support for Python 3.6
- Removed from CI
- Removed version requirement from `black` and `pre-commit`
- Removed from setup.py
- Add support for Python 3.10
- Added to CI
- Added to setup.py
Fixes #552
> Remove Python 3.6 and Add Python 3.10

- .pre-commit-config.yaml
- CHANGELOG.md
- canvasapi/course.py
* Call `combine_kwargs` on `course.get_module()` method. Keyword arguments were being omitted.
Fixes #572 .
> Call `combine_kwargs` on `course.get_module()`

- CHANGELOG.md
- canvasapi/assignment.py
- tests/fixtures/assignment.json
- tests/test_assignment.py
Add Moderated Grading endpoints:
- [List students selected for moderation](https://canvas.instructure.com/doc/api/moderated_grading.html#method.moderation_set.index)
- [Select students for moderation](https://canvas.instructure.com/doc/api/moderated_grading.html#method.moderation_set.create)
Fixes #566
> Issue #566 Moderation Set

- CHANGELOG.md
- canvasapi/course.py
- canvasapi/new_quiz.py
- canvasapi/paginated_list.py
- tests/fixtures/new_quiz.json
- tests/settings.py
- tests/test_course.py
- tests/test_new_quiz.py
* Add coverage for New Quizzes endpoints
**Note:** These endpoints follow a different base URL than most other endpoints (`/api/quiz/v1/` instead of `/api/v1/`)
Fixes #608
> New Quizzes

- CHANGELOG.md
- canvasapi/course.py
- canvasapi/requester.py
- tests/fixtures/generic_file.txt
- tests/test_course.py
Fix issue where Course.create_discussion_topic doesn't accept attachment files
Fixes #621
> Course Create Discussion Attach Files #621

- canvasapi/paginated_list.py
Include details for each parameter used in `PaginatedList`.
Fixes #651.
> Improve `PaginatedList` docs

- canvasapi/canvas.py
- canvasapi/course.py
- canvasapi/new_quiz.py
- canvasapi/requester.py
Based on #612 and as an issue in #619, this adds the `new_quizzes` and `graphql` keyword endpoints in the requester module. Methods which specify these locations will have the correct URL supplied by the library in the `_url` parameter for the requester.
Calls from the `canvas`, `course`, and `new_quizzes` modules have been updated to use they keywords rather than a formatted URL string.
All tests passing.
Fixes #619.
> Use `new_quizzes` and `graphql` keywords
