ucfopen/canvasapi

- docs/getting-started.rst
Updated Getting Started Example. Switched API_KEY and API_URL.
> updated example

- AUTHORS.md
- CHANGELOG.md
- README.md
- canvasapi/__init__.py
- canvasapi/canvas.py
- tests/fixtures/account.json
- tests/fixtures/course.json
- tests/fixtures/group.json
- tests/fixtures/section.json
- tests/test_canvas.py
Added support for SIS IDs to get accounts, courses, groups and sections.
> Release v0.6.0

- canvasapi/requester.py
- tests/test_requester.py
Added DateTime support for all endpoints. When a user passes a DateTime object, it will automatically be converted to ISO 8601 format before sending off to Canvas.
Resolves #54
> DateTime Arguments

- canvasapi/requester.py
This is a minor change; just slightly tighter code for achieving the same result as before.
> Append dictionary items to a list more concisely

- canvasapi/course.py
Fixed an issue where kwargs weren't passed along in the get_pages method
> Course.get_pages Filtering

- README.md
- docs/getting-started.rst
Updated "Getting Started" page in the documentation to match the updates to the README.
Also corrects the example of the `Course.update()` method.
Resolves #71
> Update Getting Started Page

- canvasapi/course.py
- canvasapi/group.py
- docs/getting-started.rst
- tests/fixtures/course.json
- tests/fixtures/group.json
- tests/test_course.py
- tests/test_group.py
Fixed an issue where reordering pinned topics had no valid values for the order param.
Resolves #91
> Reorder Pinned Topics fix

- canvasapi/appointment_group.py
- canvasapi/assignment.py
- canvasapi/authentication_provider.py
- canvasapi/bookmark.py
- canvasapi/calendar_event.py
- canvasapi/canvas_object.py
- canvasapi/communication_channel.py
- canvasapi/conversation.py
- canvasapi/enrollment.py
- canvasapi/enrollment_term.py
- canvasapi/external_tool.py
- canvasapi/file.py
- canvasapi/folder.py
- canvasapi/group.py
- canvasapi/login.py
- canvasapi/module.py
- canvasapi/page.py
- canvasapi/paginated_list.py
- canvasapi/progress.py
- canvasapi/quiz.py
- canvasapi/requester.py
- canvasapi/section.py
- canvasapi/user.py
- canvasapi/util.py
- tests/test_course.py
- tests/test_group.py
- tests/test_submission.py
- tests/test_uploader.py
- tests/test_user.py
Updated the formatting of strings. Example: 
'%s' % str
became 
'{}'.format(str)
> Formatting

- .gitignore
- canvasapi/account.py
- canvasapi/course.py
- canvasapi/grading_standard.py
- tests/fixtures/account.json
- tests/fixtures/course.json
- tests/test_account.py
- tests/test_course.py
- tests/test_grading_standard.py
Created 3 methods for Grading Standards in account.py and course.py.
Added tests for the added methods.
Added Visual Studio Code settings file to .gitignore.
> Implemented Grading Standards

- canvasapi/canvas.py
- canvasapi/util.py
- tests/settings.py
- tests/test_canvas.py
- tests/test_course.py
- tests/test_group.py
- tests/test_submission.py
- tests/test_uploader.py
- tests/test_user.py
- tests/test_util.py
- tests/util.py
> #115 Deprecate api version in url

- README.md
- canvasapi/account.py
- docs/getting-started.rst
- tests/fixtures/account.json
- tests/fixtures/course.json
- tests/test_account.py
- tests/test_course.py
- Added a `delete` method to `Account` to allow deletion of subaccounts.
- Changed references of `sis_login_id` in our docs to `login_id`
Resolves #106
> Updates for Canvas Release 2017-11-18

- README.md
- canvasapi/account.py
- canvasapi/course.py
- docs/class-reference.rst
- docs/getting-started.rst
- docs/rubric-ref.rst
Removed /api/v1/ references in docs.
Added Rubric documentation.
Fixed several broken links.
Resolves #123
> Docs Cleanup

- canvasapi/upload.py
Fixed an issue where Canvas returning a prepended `while(1);` would prevent uploads from completing.
> Upload Comment Fix

- canvasapi/util.py
- tests/test_util.py
> #132 Improve flexibility of get_institution_url

- README.md
- docs/getting-started.rst
> #134 Documentation Fix

- CHANGELOG.md
- README.md
- canvasapi/__init__.py
- canvasapi/group.py
- canvasapi/page.py
- canvasapi/upload.py
- canvasapi/util.py
- docs/class-reference.rst
- docs/getting-started.rst
- docs/submission-ref.rst
- tests/test_util.py
> Release v0.8.1

- CHANGELOG.md
- canvasapi/__init__.py
- canvasapi/login.py
- tests/fixtures/account.json
- tests/fixtures/login.json
- tests/test_account.py
- tests/test_login.py
Bugfix for Login delete/edit issues.
> Release v0.8.2

- canvasapi/submission.py
- tests/fixtures/submission.json
- tests/test_submission.py
Resolves #142.
Contains a _little_ hack that we need to remove once #140 is completed.
> #142 Upload comment auto-attach 

- canvasapi/account.py
- canvasapi/paginated_list.py
- tests/fixtures/account.json
- tests/test_paginated_list.py
Resolves #146 and sets us up to patch any similar issues we encounter in the future.
> #146 List enrollment terms

- canvasapi/conversation.py
- canvasapi/quiz.py
- tests/fixtures/quiz.json
- tests/test_quiz.py
> Quiz Question Methods

- canvasapi/course.py
- tests/fixtures/course.json
- tests/test_course.py
Should use `get_sections` instead
Also improve course `get_section` to allow the `include` parameter
Resolves #154
Related #156
> #154 Depricate course list_sections

- .travis.yml
- CHANGELOG.md
- canvasapi/assignment.py
- canvasapi/course.py
- canvasapi/section.py
- canvasapi/submission.py
- setup.py
- tests/fixtures/assignment.json
- tests/fixtures/course.json
- tests/fixtures/submission.json
- tests/test_assignment.py
- tests/test_course.py
- tests/test_section.py
- tests/test_submission.py
- tests/test_user.py
Moved several methods from Course and Section to Submission and Assignment. Deprecated old methods. Resolves #57
> Fix Submission Methods

- CHANGELOG.md
- README.md
- docs/examples.rst
- docs/getting-started.rst
- docs/index.rst
Work in progress. @jessemcbride is taking this one over.
Add examples to documentation (#147)
Completed so far:
- Added initial code examples for Courses and Assignments
> [WIP] Code Examples

- canvasapi/assignment.py
Pretty sure "submision" is misspelled
> Fix typo (submision => submission)

- docs/examples.rst
#147 Updated examples.rst with correct method for getting user logins. Wasn't sure if I could update my existing pull request so I created a new one. Please delete the other one.
> #147 Updated examples.rst with correct method for getting user logins

- canvasapi/canvas.py
- tests/fixtures/account.json
- tests/fixtures/assignment.json
- tests/fixtures/authentication_providers.json
- tests/fixtures/conversation.json
- tests/fixtures/course.json
- tests/fixtures/current_user.json
- tests/fixtures/external_tool.json
- tests/fixtures/folder.json
- tests/fixtures/group.json
- tests/fixtures/login.json
- tests/fixtures/module.json
- tests/fixtures/outcome.json
- tests/fixtures/page.json
- tests/fixtures/paginated_list.json
- tests/fixtures/section.json
- tests/fixtures/submission.json
- tests/fixtures/uploader.json
- tests/fixtures/user.json
- tests/settings.py
- tests/test_canvas.py
- tests/test_course.py
- tests/test_group.py
> #183 Warn users that requests may behave unexpectedly over HTTP instead of HTTPS

- canvasapi/module.py
@mdmairet found two missing calls to combine_kwargs in module.edit
> add combine_kwargs call to module.edit

- README.md
- docs/getting-started.rst
- docs/index.rst
- docs/keyword-args.rst
Added more detailed documentation for Keyword Arguments.
> Kwarg Docs

- canvasapi/assignment.py
- canvasapi/course.py
- canvasapi/group.py
- canvasapi/section.py
- tests/fixtures/assignment.json
- tests/fixtures/group.json
- tests/test_assignment.py
- tests/test_course.py
- tests/test_group.py
- tests/test_section.py
Adds coverage for Assignment Override endpoints.
See #216
> Issue #216 Assignment Overrides

- AUTHORS.md
- CHANGELOG.md
- canvasapi/communication_channel.py
- canvasapi/user.py
- tests/fixtures/communication_channel.json
- tests/fixtures/user.json
- tests/test_communication_channel.py
- tests/test_user.py
Pretty simple modification: Adds user.create_communication_channel() and communication_channel.delete(), as it ended up being useful for me to have these. 
Please let me know if I overlooked anything!
> Issue #231 - Feature/create delete communucation channels

- canvasapi/assignment.py
- canvasapi/peer_review.py
- canvasapi/submission.py
- tests/fixtures/assignment.json
- tests/fixtures/submission.json
- tests/test_assignment.py
- tests/test_peer_review.py
- tests/test_submission.py
**Description**: cover endpoints for peer reviews (https://canvas.instructure.com/doc/api/peer_reviews.html)
**Endpoints covered**:
* Get all Peer Reviews
- GET /api/v1/courses/:course_id/assignments/:assignment_id/peer_reviews
- GET /api/v1/courses/:course_id/assignments/:assignment_id/submissions/:submission_id/peer_reviews
* Create Peer Review
- POST /api/v1/courses/:course_id/assignments/:assignment_id/submissions/:submission_id/peer_reviews
* Delete Peer Review
- DELETE /api/v1/courses/:course_id/assignments/:assignment_id/submissions/:submission_id/peer_reviews
resolve issue #244
> Issue #244 peer reviews

- canvasapi/account.py
add required parameters to request call, in addition to optional kwargs
Fixes #249
> issue/249 - adding required parameters to request

- CHANGELOG.md
- canvasapi/requester.py
- tests/fixtures/requests.json
- tests/test_requester.py
* Add generic error handling for 4XX and above HTTP errors
Fixes #224.
> Issue #224 Generic HTTP Error Handling

- AUTHORS.md
- CHANGELOG.md
- canvasapi/requester.py
- tests/fixtures/requests.json
- tests/test_requester.py
* Add support for PATCH HTTP method.
* Formatting tweaks
Adapted from @us91's code provided in #215.
Fixes #215.
> Add support for PATCH method

- docs/exceptions.rst
- docs/index.rst
* Adds basic documentation of our exceptions.
Fixes #243.
> Issue #243 Add documentation for Exceptions

- canvasapi/quiz.py
- canvasapi/requester.py
- tests/fixtures/submission.json
- tests/test_quiz.py
* Add coverage for Quiz Submission Questions endpoint.
Resolves #272 on completion.
> #272 Quiz Submission Questions

- CHANGELOG.md
- canvasapi/requester.py
- canvasapi/util.py
- docs/debugging.rst
- docs/index.rst
- tests/test_util.py
* Add logger statements in `canvasapi.requester` to log requester activity.
* Add `util.clean_headers` to sanitize authentication tokens from log outputs.
* Add documentation on logging at `docs/debugging.rst`
Fixes #235
> #235 Verbose mode

- canvasapi/collaboration.py
- canvasapi/course.py
- canvasapi/group.py
- docs/class-reference.rst
- docs/collaboration-ref.rst
- tests/fixtures/collaboration.json
- tests/fixtures/course.json
- tests/fixtures/group.json
- tests/test_collaboration.py
- tests/test_course.py
- tests/test_group.py
- Covered List collaborations
- Covered List collaborators.
Resolves #291
> Issue #291 Collaborations

- canvasapi/canvas.py
- tests/fixtures/account.json
- tests/test_canvas.py
Add `brand_variables` endpoint.
Fixes #311
> Add brand_variables endpoint

- canvasapi/assignment.py
* Add `_kwargs` to AssignmentOverride `edit` and `delete` methods
Fixes # 314.
> Fix AssignmentOverride edit and delete

- canvasapi/quiz.py
* Add course_id when creating QuizSubmission objects
Fixes #316.
> QuizSubmission Course ID

- canvasapi/util.py
Use `iter()` instead of checking if instance `Iterable`. See https://github.com/ucfopen/canvasapi/issues/284#issuecomment-533184311 for explanation.
Fixes #284.
> Update iterable check

- canvasapi/quiz.py
- tests/fixtures/quiz.json
- tests/test_quiz.py
* Fetching the latest quiz statistics
Fixes #345
> Add quiz statistics endpoint

- canvasapi/course.py
- canvasapi/quiz.py
- docs/quiz-ref.rst
- tests/fixtures/course.json
- tests/test_course.py
- tests/test_quiz.py
* Added method to get quiz assignment override
Fixes #348
> Quiz Assignment Override

- README.md
enrollment_status => enrollment_state
Canvas uses enrollment_state to determine if a user is currently enrolled or not.
*
*
Fixes # .
> Updated documentation to reflect API change

- canvasapi/course.py
No algorithmic changes.  Docstring fixed in create_page, fixing parameter name and return type to fix the docs.
> fixing minor docstring errors in course.create_page

- canvasapi/canvas.py
- tests/test_canvas.py
Fix an issue where base_url was being set incorrectly.
Added regression test.
Fixes #389 
Fixes #390
> Fix API_URL

- CHANGELOG.md
- canvasapi/__init__.py
> Release v0.16.1

- .travis.yml
* Upgrade from `xenial` to `bionic`
Fixes #393.
> Upgrade Ubuntu dist on Travis to bionic

- .travis.yml
- CHANGELOG.md
- DEPLOY.md
* Set up Travis to deploy on tags
Fixes #360.
> PyPI Deployment via Travis

- canvasapi/module.py
- tests/test_module.py
* Solved issue of RequiredFieldError incorrectly appearing for types SubHeader, ExternalURL, and Page
Fixes #350
> Issue #350 create module item

- canvasapi/canvas.py
- canvasapi/course.py
- canvasapi/progress.py
- canvasapi/user.py
- tests/test_authentication_event.py
- tests/test_blueprint.py
- tests/test_content_migration.py
- tests/test_course.py
- tests/test_poll_submission.py
* Run latest version of `black` to update formatting
Fixes #412
> Update formatting to latest black version

- README.md
* URL changed from latest to stable
> Fixup broken links to readthedocs in README

- canvasapi/canvas.py
- docs/current-user-ref.rst
* Added Docstring to get_user_method in canvas.py
* Added some Documentation in current-user-ref.rst explaining the inheritance of current_user class from the User class
* Added the reference to the User class 
Fixes #367
> Solved Issue #367 CurrentUser Documentation

- docs/getting-started.rst
* Add documentation for our "Smart DateTimes" feature
> Documentation for Smart DateTimes

- CHANGELOG.md
- docs/index.rst
- docs/troubleshooting.rst
* Add basic troubleshooting guide to documentation
Fixes #414.
> Troubleshooting Page

- canvasapi/course.py
* change return type for Course.get_page() from Course to Page
* change return type for Course.get_pages() from PaginatedList of Course to PaginatedList of Page
Fixes #451
> Fix return type for get_page and get_pages

- setup.py
Updated setup.py to use the README information for the PyPI long description.
This is documented by the PSF here:
https://packaging.python.org/guides/making-a-pypi-friendly-readme/
Fixes #449
> Update PyPI package description

- canvasapi/section.py
- tests/fixtures/section.json
- tests/test_section.py
* enroll_user function added to canvasapi/section.py
* associated tests and fixtures added
Fixes #364 .
> Added section.enroll_user (fixes ucfopen#364)

- .github/workflows/run-tests.yml
- CHANGELOG.md
- scripts/find_missing_kwargs.py
- setup.cfg
* Add GitHub actions flow:
```   
- name: Lint with flake8
run: flake8
- name: Check formatting
run: black --check canvasapi tests
- name: Sort imports
run: isort --check canvasapi tests
- name: Run tests
run: coverage run -m unittest discover
- name: Lint markdown files
uses: bewuethr/mdl-action@v1
- name: Check if methods are alphabetical
run: python scripts/alphabetic.py
- name: Check for missing kwargs
run: python scripts/find_missing_kwargs.py
```
* Add flake8 configs for displaying output to `setup.cfg`:
```
exclude = .git,__pycache__,docs/conf.py,old,build,dist
statistics = True
show_source = True
```
Fixes #445.
> #445 GitHub Actions

- .github/workflows/run-tests.yml
Updates GitHub actions to run on pushes to a branch in a PR.
> Run GH Actions on PR events

- .github/workflows/run-tests.yml
- CHANGELOG.md
- setup.py
* Add support for Python 3.9
* Bump development status from "alpha" to "production"
Intentionally didn't update `.travis.yml` since Travis is dead to us.
Fixes #472
> Python 3.9

- .github/workflows/run-tests.yml
* Add CodeCov action
* Set actions to only run on `master` and `develop` branches
Fixes #475
> Issue #475 GitHub Actions Coverage

- README.md
Update Slack link and badge.
Fixes #544
> Update ucf open slack badge and link

- README.md
Replace Travis CI badge with GitHub Actions badge
Fixes #548.
> GitHub Actions badge

- README.md
Update coverage badge from coveralls to codecov
Fixes #550
> Update Coverage Badge

- AUTHORS.md
- CHANGELOG.md
- canvasapi/user.py
* Pass through kwargs to the server. Most calls do this. A useful kwargs for get_profile is include=["links"]
> Pass through optional parameters in get_profile()

- .github/workflows/run-tests.yml
- CHANGELOG.md
- Upgrades Codecov Action from v1 to v3
Fixes #557
> Upgrade Codecov action version

- AUTHORS.md
- CHANGELOG.md
- canvasapi/appointment_group.py
- canvasapi/canvas.py
* canvas.py seems to have the same raise statement scenario. Consider verifying if that needs an update as well.
Fixes #430 .
> Fixed raise statement typo in appointment_group.py

- canvasapi/rubric.py
- docs/rubric-ref.rst
- tests/fixtures/rubric.json
- tests/test_rubric.py
Add endpoints for managing `RubricAssessments`.
Fixes #538.
> Issue 538 Rubric endpoint coverage

- .github/workflows/run-tests.yml
- CHANGELOG.md
- setup.py
> Add support for Python 3.11

- .github/workflows/run-tests.yml
Updates Codecov Action from v3 to v4 in hopes of fixing recent issues with the pipeline.
> Update Codecov Action

- canvasapi/paginated_list.py
* Update regex to add new_quizzes_url in paginated_list
*
Fixes # 663
> Fixes #663 - New Quizzes URL not considered in paginated_list
